name: Rust

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: npm installation
      run: npm install
    - name: Build
      run: cargo install tauri-cli && cargo tauri build --verbose
    - name: Run tests
      run: cargo tauri test --verbose
